/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./frontend/**/*.{html,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-bright": "#31394d",
        "on-tertiary-fixed-variant": "#3c475a",
        "tertiary-fixed": "#d8e3fb",
        "primary-fixed-dim": "#c0c1ff",
        "inverse-on-surface": "#283044",
        "surface": "#0b1326",
        "surface-container": "#171f33",
        "tertiary-container": "#8691a7",
        "on-tertiary-fixed": "#111c2d",
        "on-primary": "#1000a9",
        "surface-dim": "#0b1326",
        "outline": "#908fa0",
        "error-container": "#93000a",
        "surface-container-low": "#131b2e",
        "on-secondary-fixed": "#0d1c2e",
        "surface-variant": "#2d3449",
        "on-error": "#690005",
        "on-tertiary-container": "#1f2a3c",
        "on-secondary": "#233144",
        "secondary-fixed": "#d5e3fc",
        "on-surface": "#dae2fd",
        "on-primary-fixed": "#07006c",
        "outline-variant": "#464554",
        "secondary-container": "#3c4a5e",
        "secondary-fixed-dim": "#b9c7df",
        "inverse-primary": "#494bd6",
        "on-primary-container": "#0d0096",
        "inverse-surface": "#dae2fd",
        "on-tertiary": "#263143",
        "surface-tint": "#c0c1ff",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-background": "#dae2fd",
        "background": "#0b1326",
        "tertiary-fixed-dim": "#bcc7de",
        "primary-container": "#8083ff",
        "primary-fixed": "#e1e0ff",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "on-secondary-fixed-variant": "#3a485b",
        "surface-container-lowest": "#060e20",
        "tertiary": "#bcc7de",
        "primary": "#c0c1ff",
        "on-surface-variant": "#c7c4d7",
        "error": "#ffb4ab",
        "on-secondary-container": "#abb9d1",
        "secondary": "#b9c7df"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"]
      },
      borderRadius: {
        none: "0",
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.75rem",
        full: "9999px"
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
